name: Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install lcov
        sudo apt-get install libcriterion-dev
        sudo apt-get install gcovr
    - name: Run tests
      run: |
        cd mars_lib
        make tests_run
        lcov --directory $(pwd) --capture --output-file coverage.info
    - name: Generate coverage report
      run: |
        genhtml coverage.info --output-directory out
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage.info
        token: ${{ secrets.CODECOV_TOKEN }}
